### PR TITLE
Major changes for easier SharedMedia. 

### PR DESCRIPTION
**Pull request by Goranaws**
Let's see what you think...

### CODE REVIEW

**Comment by Goranaws** [comment]
I did not change localization.ru.lua

not sure why it says so....

**Comment by Tuller** [comment]
Probably whitespace changes

**Comment by Tuller** [comment]
Notes:
The Blizzard castbar still appears when using the Dominos one, and the bar itself doesn't seem to have a size after a /dom reset:
image

**Comment by Goranaws** [comment]
I've added an advance option that handles this. It will now hide the Blizzard bar by default. Also, I'm not having any size issues after a /dom reset... I'm going to do more testing.

**Pull request merged**
